DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS post;

CREATE TABLE games (
  id TEXT PRIMARY KEY,
  num_piles INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE positions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  piles TEXT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES games (id)
);